#!/usr/bin/python
# -*- coding: utf-8 -*-

# strategy.py

from __future__ import print_function

from abc import ABCMeta, abstractmethod

try:
    import Queue as queue
except ImportError:
    import queue


class Strategy(object):

    '''
    starategy generate signal based on the data/bar/OHLCV generated by dataHandler

    '''

    __metaclass__ = ABCMeta
    #同理data handler，先在parent class建立各种abc 方程，稍后在子class override
    @abstractmethod
    def calculate_signals(self):
        raise NotImplementedError("Should implement calculate_signals()")


